# Generated by Django 5.0.4 on 2024-04-16 21:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_post_userpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPost',
            new_name='Post',
        ),
    ]
